gdt050579/AppCUI

- .gitignore
- AppCUI/AppCUI.cpp
- AppCUI/include/IO.h
- AppCUI/src/Application/Application.cpp
- AppCUI/src/Application/CMakeLists.txt
- AppCUI/src/Application/CommandBarController.cpp
- AppCUI/src/Application/Config.cpp
- AppCUI/src/Application/ConsoleRenderer.cpp
- AppCUI/src/Application/Desktop.cpp
- AppCUI/src/Application/WindowsImplementation.cpp
- AppCUI/src/CMakeLists.txt
- AppCUI/src/Console/CMakeLists.txt
- AppCUI/src/Console/Clip.cpp
- AppCUI/src/Console/Rect.cpp
- AppCUI/src/Console/Renderer.cpp
- AppCUI/src/Controls/CMakeLists.txt
- AppCUI/src/Controls/Control.cpp
- AppCUI/src/Utils/CMakeLists.txt
- AppCUI/src/Utils/KeyUtils.cpp
- AppCUI/src/Utils/String.cpp
- CMakeLists.txt
- Tester/Tester.cpp
- build.sh
+ dummy CHAR_INFO structure
+ some gcc compiler complaints (preprocessor fixes)
> Cmake + dummy macos compilation of lib

- AppCUI/src/Application/MacImplementation.cpp
- CMakeLists.txt
- Tester/Tester.cpp
- basic unix implementation with ncurses
- doesn't necessarily work but doesn't crash either
- minor cmake additions
> Feature macbasic

- .github/workflows/codeql-analysis.yml
Added initial variant for CodeQL analyzer
> Added CodeQL code analyzer

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
#88 Added bug report and feature request templates
> Added bug report and feature request templates

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Controls/ListView.cpp
- Examples/ListView/main.cpp
- Examples/Snake/Board.cpp
- Examples/Snake/Snake.cpp
- Examples/Snake/Snake.hpp
> Snake with colors #255

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Application/Config.cpp
- AppCUI/src/ControlContext.hpp
- AppCUI/src/Controls/Grid.cpp
- AppCUI/src/Controls/ListView.cpp
- AppCUI/src/Controls/NumericSelector.cpp
- AppCUI/src/Controls/PropertyList.cpp
- AppCUI/src/Controls/Tree.cpp
- Examples/TreeView/main.cpp
numeric selector & tree view for now
> New color config format

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Controls/TreeView.cpp
> + tree view - item - get parent

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Controls/TreeView.cpp
> + tree view - set/get text for subitem

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Utils/String.cpp
> # String - fixes

- AppCUI/src/Controls/TreeView.cpp
> ^ tree view - modified logic (shift+) enter/space

- AppCUI/include/AppCUI.hpp
- AppCUI/src/ControlContext.hpp
- AppCUI/src/Controls/TreeView.cpp
> ^ tree view - renamed item selected to current

- AppCUI/include/AppCUI.hpp
- AppCUI/src/OS/DateTime.cpp
> + filetime -> datetime

- AppCUI/src/ControlContext.hpp
- AppCUI/src/Controls/TreeView.cpp
> + tree view - jump to found element when searched

- AppCUI/src/OS/Windows/File.cpp
> # windows - file - fix long path on CreateFile

- AppCUI/include/AppCUI.hpp
- AppCUI/src/OS/DateTime.cpp
> + datetime - from FAT UTC

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Controls/TreeView.cpp
- AppCUI/src/OS/DateTime.cpp
- AppCUI/src/OS/Windows/File.cpp
> # file - windows - long path separator sanitize

- Examples/BadApple/main.cpp
- Examples/Logo/main.cpp
- Examples/RemoveControl/main.cpp
- docs/source/index.rst
> + examples - fixes

- AppCUI/CMakeLists.txt
- CMakeLists.txt
- cmake/example.cmake
> [Build] + LTO

- AppCUI/src/Terminal/WindowsTerminal/WindowsTerminal.cpp
This solves https://github.com/gdt050579/GView/issues/235.
> 235 core adjust the size of the terminal to the screen height

- AppCUI/include/AppCUI.hpp
- AppCUI/src/Controls/TreeView.cpp
- AppCUI/src/Dialogs/FileDialog.cpp
This solves https://github.com/gdt050579/GView/issues/267.
> 267 containerviewtreeview add tooltip to search area
